/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/collectibles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse the acting collector's collection
         * @description Returns one page of the acting collector's collectibles, most recently added first (FR-034),
         *     optionally narrowed to a single collection status (FR-037). Never returns another collector's
         *     collectibles (FR-026).
         *
         *     Paging is by opaque cursor. An empty `items` array with no `nextCursor` means there is
         *     nothing further; whether that represents an empty vault or a filter matching nothing is
         *     distinguished by `totalUnfiltered` (FR-040 versus FR-041).
         */
        get: operations["listCollectibles"];
        put?: never;
        /**
         * Add a collectible to the acting collector's vault
         * @description Creates one collectible owned by the acting collector (FR-001). A name and a collection
         *     status are required; every other attribute is optional (FR-002, FR-005, FR-006).
         *
         *     Every request carries a `submissionKey` the client generates per add attempt. Replaying the
         *     same key within the idempotency window returns the collectible that key already created,
         *     rather than creating a second one (FR-047) — so a double-click or a retry after a lost
         *     response cannot strand the collector with an undeletable duplicate.
         *
         *     A request with a *different* key creates an independent collectible even when every other
         *     value is identical; deliberate duplicates are never merged or de-duplicated (FR-023).
         *
         *     All validation problems are reported together in a single response (FR-020).
         */
        post: operations["addCollectible"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a primary image
         * @description Accepts one image file, validates it by decoding rather than by its declared type
         *     (FR-009), enforces the 10 MB limit (FR-010), applies EXIF orientation, derives the
         *     fixed-aspect gallery rendition (FR-014), and stores both.
         *
         *     Returns an image identifier to pass as `imageId` when adding a collectible. Uploading is
         *     separate from adding precisely so a refused image never blocks saving the rest of the
         *     collectible (FR-013).
         *
         *     A refused upload stores nothing.
         */
        post: operations["uploadCollectibleImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{imageId}/rendition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the gallery rendition of an image
         * @description Returns the fixed-aspect gallery rendition bytes. Authorization is checked on every request:
         *     only the collector who owns the image receives it, and possessing the address grants nothing
         *     (FR-015). An image belonging to another collector responds 404, indistinguishable from one
         *     that does not exist (FR-027).
         *
         *     This is the address the gallery's `<img>` elements use. It is reached through the same-origin
         *     rewrite so the session cookie accompanies the request.
         */
        get: operations["getImageRendition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The state of a collectible in the collector's vault. Exactly these four (FR-004).
         * @enum {string}
         */
        CollectionStatus: "owned" | "preordered" | "wishlist" | "sold";
        /**
         * @description An exact decimal amount as a string, with at most two fractional digits. Carried as a string,
         *     never a JSON number, so no floating-point conversion can occur anywhere in the path
         *     (Principle IV). `"0.00"` is a recorded amount, distinct from the field being absent (FR-007,
         *     FR-017).
         * @example 0.00
         * @example 249.99
         * @example 1250.00
         */
        MonetaryAmount: string;
        /**
         * @description Values for a new collectible. `name` and `collectionStatus` are required; everything else is
         *     optional (FR-005, FR-006). An omitted field means the collector recorded nothing, which is
         *     distinct from an empty string or zero (FR-007).
         * @example {
         *       "submissionKey": "01J8Z3K7QX4M9V2N6P0R5T8W1Y",
         *       "name": "Kaiju Sentinel",
         *       "collectionStatus": "owned"
         *     }
         * @example {
         *       "submissionKey": "01J8Z3M2WB7C4D9F1G6H0J5K3L",
         *       "name": "Kaiju Sentinel",
         *       "collectionStatus": "owned",
         *       "character": "Sentinel Prime",
         *       "series": "Kaiju Wars",
         *       "manufacturer": "Apex Studio",
         *       "category": "Statue",
         *       "scale": "1/4",
         *       "edition": "Deluxe Exclusive",
         *       "purchasePrice": "1250.00",
         *       "purchaseDate": "2026-08-14",
         *       "releaseDate": "2026-11-30",
         *       "notes": "Box has a small dent on the lower left corner.",
         *       "imageId": "6f9619ff-8b86-d011-b42d-00cf4fc964ff"
         *     }
         */
        AddCollectibleRequest: {
            /**
             * @description A key the client generates once per add attempt and replays on retry. Replaying it
             *     within the idempotency window returns the collectible it already created instead of
             *     creating another (FR-047). A new key always creates an independent collectible, which
             *     is what keeps deliberate duplicates working (FR-023).
             *
             *     Regenerate it only when the collector starts a new collectible — never per keystroke,
             *     and never per network attempt.
             * @example 01J8Z3K7QX4M9V2N6P0R5T8W1Y
             */
            submissionKey: string;
            /** @description Required. Rejected if empty once surrounding whitespace is removed (FR-003). */
            name: string;
            collectionStatus: components["schemas"]["CollectionStatus"];
            character?: string | null;
            /** @description The series or franchise. */
            series?: string | null;
            manufacturer?: string | null;
            category?: string | null;
            scale?: string | null;
            /** @description The edition or variant. */
            edition?: string | null;
            purchasePrice?: components["schemas"]["MonetaryAmount"] | null;
            /**
             * Format: date
             * @description A calendar date, not later than today (FR-018).
             */
            purchaseDate?: string | null;
            /**
             * Format: date
             * @description A calendar date, past or future, in any combination with the other values (FR-019).
             */
            releaseDate?: string | null;
            notes?: string | null;
            /**
             * Format: uuid
             * @description Identifier returned by a prior upload. Must name an image owned by the acting collector
             *     (FR-015). At most one image per collectible (FR-011); omit for none (FR-012).
             */
            imageId?: string | null;
        };
        /** @description One collectible in the acting collector's vault. */
        Collectible: {
            /** Format: uuid */
            id: string;
            name: string;
            collectionStatus: components["schemas"]["CollectionStatus"];
            character?: string | null;
            series?: string | null;
            manufacturer?: string | null;
            category?: string | null;
            scale?: string | null;
            edition?: string | null;
            purchasePrice?: components["schemas"]["MonetaryAmount"] | null;
            /** Format: date */
            purchaseDate?: string | null;
            /** Format: date */
            releaseDate?: string | null;
            notes?: string | null;
            /**
             * @description Absent when the collector supplied no image; the gallery shows its designed placeholder
             *     instead (FR-033).
             */
            image?: components["schemas"]["CollectibleImageRef"] | null;
            /**
             * Format: date-time
             * @description When the collectible was added. The default gallery order (FR-034).
             */
            createdAt: string;
        };
        /** @description How the gallery reaches a collectible's image. */
        CollectibleImageRef: {
            /** Format: uuid */
            id: string;
            /**
             * @description Path of the gallery rendition, authorized on every request (FR-015). Same-origin, so the
             *     session cookie accompanies the `<img>` request.
             * @example /api/images/6f9619ff-8b86-d011-b42d-00cf4fc964ff/rendition
             */
            renditionUrl: string;
            /** @description Rendition width in pixels. Identical for every rendition (FR-014). */
            width: number;
            /** @description Rendition height in pixels. Identical for every rendition (FR-014). */
            height: number;
        };
        /** @description An accepted upload, ready to attach to a collectible. */
        CollectibleImage: {
            /**
             * Format: uuid
             * @description Pass as `imageId` when adding a collectible.
             */
            id: string;
            renditionUrl: string;
            /**
             * @description What the decode determined, never what the client declared (FR-009).
             * @enum {string}
             */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            /** @description Size of the accepted upload in bytes; at most 10485760 (FR-010). */
            byteSize: number;
            width: number;
            height: number;
        };
        /** @description One page of the acting collector's collection. */
        CollectionPage: {
            /** @description Entries in this page, most recently added first (FR-034). */
            items: components["schemas"]["Collectible"][];
            /** @description Cursor for the following page, or absent when this is the last page (FR-035). */
            nextCursor?: string | null;
            /**
             * @description How many collectibles the collector has in total, ignoring any status filter. Lets the
             *     frontend tell an empty vault (FR-041) from a filter that matched nothing (FR-040)
             *     without a second request.
             */
            totalUnfiltered: number;
        };
        /**
         * @description The single error envelope for every failing operation. Carries codes the frontend can act on
         *     and messages fit to show a collector; never internal detail (Principle IV).
         */
        ErrorResponse: {
            error: {
                /**
                 * @description Stable, machine-readable classification of the failure.
                 * @example validation_failed
                 * @example unauthenticated
                 * @example not_found
                 * @example image_too_large
                 * @example unsupported_image_format
                 * @example internal_error
                 */
                code: string;
                /** @description A message suitable for display to a collector. */
                message: string;
                /**
                 * @description One entry per offending field. Present when the failure is a validation failure; all
                 *     problems appear together (FR-020).
                 */
                fields?: {
                    /** @description Name of the offending request field. */
                    field: string;
                    /**
                     * @example required
                     * @example invalid_value
                     * @example negative_amount
                     * @example date_in_future
                     * @example too_long
                     * @example unknown_image
                     */
                    code: string;
                    message: string;
                }[];
            };
        };
    };
    responses: {
        /**
         * @description The request was rejected. Every validation problem found is reported together, not one at a
         *     time (FR-020).
         */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The acting collector could not be resolved. No collection content is returned (FR-029). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description No such resource for the acting collector. Returned identically whether the resource does
         *     not exist or belongs to another collector, so existence is never revealed (FR-027).
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request body's media type is not supported by this operation. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected failure. The response carries no internal detail (Principle IV). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCollectibles: {
        parameters: {
            query?: {
                /** @description Narrow to one collection status. Omit for all statuses (FR-038). */
                status?: components["schemas"]["CollectionStatus"];
                /** @description Opaque cursor from a previous response's `nextCursor`. Omit for the first page. */
                cursor?: string;
                /** @description Maximum entries to return in this page. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the collection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPage"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["InternalError"];
        };
    };
    addCollectible: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCollectibleRequest"];
            };
        };
        responses: {
            /**
             * @description The collectible was added.
             *
             *     Also returned when a `submissionKey` is replayed within the idempotency window, carrying
             *     the collectible that key already created. The status is deliberately identical: the
             *     client cannot distinguish the two cases and has no need to — in both, exactly one
             *     collectible exists for that key (FR-047).
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collectible"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    uploadCollectibleImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description One image file — JPEG, PNG, or WebP, at most 10 MB.
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The image was accepted and stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectibleImage"];
                };
            };
            /**
             * @description The file was not a decodable JPEG, PNG, or WebP image. The error names the accepted
             *     formats (FR-009).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            /** @description The file exceeded the 10 MB limit. The error states the limit (FR-010). */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            415: components["responses"]["UnsupportedMediaType"];
            500: components["responses"]["InternalError"];
        };
    };
    getImageRendition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rendition bytes. */
            200: {
                headers: {
                    /** @description Private caching only; a rendition must never be cached by a shared cache. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
