import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import nextPlugin from '@next/eslint-plugin-next'
import reactHooks from 'eslint-plugin-react-hooks'

/**
 * Flat config, written directly rather than through eslint-config-next.
 *
 * That package still ships an eslintrc-era compatibility patch which does not load under ESLint 9,
 * so its rules are pulled in from the underlying plugins instead. The gate is the same; only the
 * plumbing differs.
 */
export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'coverage/**',
      'test-results/**',
      'playwright-report/**',
      // Generated from contracts/openapi.yaml; not hand-maintained, so not linted.
      'lib/types/api.ts',
      // Generated by Next on every build.
      'next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: { '@next/next': nextPlugin, 'react-hooks': reactHooks },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      ...reactHooks.configs.recommended.rules,

      // Constitution Principle III: `any` SHOULD NOT be used without a documented technical
      // reason. An error rather than a warning, so it cannot accumulate quietly.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Tests reach for globals the app code does not.
    files: ['tests/**/*.{ts,tsx}'],
    rules: { '@typescript-eslint/no-non-null-assertion': 'off' },
  },
)
