package unit

import (
	"net/http"
	"testing"

	"github.com/joshuel09/vaultory/backend/internal/identity"
)

// The fixture below was produced by Better Auth's own signer, not by Go:
//
//	require('better-call/dist/crypto.cjs').signCookieValue(token, secret)
//
// That distinction is the point of this test. A fixture generated by our own code would prove
// only that our signer agrees with our verifier, which is true of any pair of functions and says
// nothing about whether Go can read what Better Auth writes.
//
// It also caught something a self-made fixture would have hidden: the value arrives URL-encoded,
// because the signature is *standard* base64 and contains "+" and "=" — %2B and %3D below.
const (
	fixtureSecret = "dev-only-not-a-real-secret-change-me"
	fixtureToken  = "kJ8xQ2mN4pR7vT1wY6zA3bC5dE9fG0hI"
	fixtureCookie = "kJ8xQ2mN4pR7vT1wY6zA3bC5dE9fG0hI.b5HvQSDwnJ7kwcZiK4Yyc23jHWuFwOxXtFvAS1%2BI1Oc%3D"
)

func request(t *testing.T, cookie string) *http.Request {
	t.Helper()
	r, err := http.NewRequest(http.MethodGet, "/api/collectibles", nil)
	if err != nil {
		t.Fatalf("build request: %v", err)
	}
	if cookie != "" {
		r.AddCookie(&http.Cookie{Name: "better-auth.session_token", Value: cookie})
	}
	return r
}

func TestVerifiesACookieSignedByBetterAuth(t *testing.T) {
	r := identity.NewSessionResolver(nil, fixtureSecret)

	token, ok := identity.ExportedVerify(r, fixtureCookie)
	if !ok {
		t.Fatal("a cookie signed by Better Auth was rejected; Go and the library disagree " +
			"about the signature format")
	}
	if token != fixtureToken {
		t.Fatalf("extracted %q, want %q", token, fixtureToken)
	}
}

func TestRejectsTamperedAndMalformedCookies(t *testing.T) {
	r := identity.NewSessionResolver(nil, fixtureSecret)

	cases := map[string]string{
		"empty":                   "",
		"token with no signature": fixtureToken,
		"signature only":          ".b5HvQSDwnJ7kwcZiK4Yyc23jHWuFwOxXtFvAS1%2BI1Oc%3D",
		"trailing separator":      fixtureToken + ".",
		"corrupted signature":     fixtureToken + ".AAAAQSDwnJ7kwcZiK4Yyc23jHWuFwOxXtFvAS1%2BI1Oc%3D",
		"altered token":           "XX8xQ2mN4pR7vT1wY6zA3bC5dE9fG0hI.b5HvQSDwnJ7kwcZiK4Yyc23jHWuFwOxXtFvAS1%2BI1Oc%3D",
		"base64url signature":     fixtureToken + ".b5HvQSDwnJ7kwcZiK4Yyc23jHWuFwOxXtFvAS1-I1Oc",
	}
	for name, cookie := range cases {
		if _, ok := identity.ExportedVerify(r, cookie); ok {
			t.Errorf("%s: accepted, want rejected", name)
		}
	}
}

// A different secret must not verify. This is what makes the secret load-bearing rather than
// decorative: hold a different one and every session is unreadable.
func TestRejectsACookieSignedWithAnotherSecret(t *testing.T) {
	r := identity.NewSessionResolver(nil, "a-completely-different-secret-value-32")
	if _, ok := identity.ExportedVerify(r, fixtureCookie); ok {
		t.Error("a cookie signed with a different secret verified")
	}
}

func TestResolveRefusesWhenNoCookieIsPresent(t *testing.T) {
	r := identity.NewSessionResolver(nil, fixtureSecret)
	if _, err := r.Resolve(request(t, "")); err != identity.ErrUnresolved {
		t.Errorf("got %v, want ErrUnresolved", err)
	}
}
